- name: configure frontend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.package:
      name: ngnix
      state: present

  - name: start nginx server
    ansible.builtin.service:
      name: ngnix
      state: started
      enabled: yes 

  - name: remove html directory
    ansible.builtin.file:
      path: /usr/share/ngnix/html
      state: absent

  
  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/ngnix/html
      state: directory

  - name: download the frontend code
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  
  - name: extract the code
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy expense conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
      name: ngnix
      state: restarted

